name: Build

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run:  |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload release asset
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}